/**
 * Mapping du dataset plantfolio-common-plants (952 plantes, CC BY-NC-SA 4.0,
 * https://github.com/Luminoid/plantfolio-common-plants -- sources citees :
 * Plants of the World Online/Kew pour la nomenclature, ASPCA pour la
 * toxicite, USDA pour les zones de rusticite) vers notre `LibraryCareProfile`.
 *
 * Import statique en local (pas d'API live) : le fichier `plantfolioData.json`
 * est une copie telechargee une fois de `dist/common_plants.json`, seedee
 * comme n'importe quelle autre entree de bibliotheque (source="PLANTFOLIO").
 */
import type { LibraryCareProfile } from "./librarySeed";

export interface PlantfolioRawEntry {
  id: string;
  typeName: string;
  description?: string;
  commonExamples?: string;
  careTips?: string;
  origin?: string;
  springInterval?: number | null;
  summerInterval?: number | null;
  fallInterval?: number | null;
  winterInterval?: number | null;
  lightPreference?: string;
  humidityPreference?: string;
  temperaturePreference?: [number, number];
  plantToxicity?: string;
  soilPhPreference?: string;
  drainagePreference?: string;
  wateringMethod?: string;
  plantLifeSpan?: [number, number];
  category?: string;
  hardinessZones?: [number, number];
  growthRate?: string;
  propagationMethods?: string[];
}

const LIGHT_LABEL: Record<string, string> = {
  lowIndirect: "Lumière faible indirecte",
  mediumIndirect: "Lumière moyenne indirecte",
  brightIndirect: "Lumière vive indirecte",
  strongDirect: "Lumière directe forte",
  outdoorPartialSun: "Extérieur, mi-ombre",
  outdoorFullSun: "Extérieur, plein soleil",
  outdoorShade: "Extérieur, ombre",
};

const HUMIDITY_LABEL: Record<string, string> = { low: "Faible", medium: "Moyenne", high: "Élevée", veryHigh: "Très élevée" };
const TOXICITY_LABEL: Record<string, string> = {
  toxic: "Toxique",
  mildlyToxic: "Légèrement toxique",
  nonToxic: "Non toxique",
  unknown: "Inconnue",
};
const PH_LABEL: Record<string, string> = { neutral: "neutre", acidic: "acide", adaptable: "adaptable", alkaline: "alcalin" };
const DRAINAGE_LABEL: Record<string, string> = {
  wellDraining: "bien drainant",
  excellentDrainage: "drainage excellent",
  moistureRetentive: "retient l'humidité",
  waterloggingTolerant: "tolère l'engorgement",
};
const GROWTH_LABEL: Record<string, string> = { slow: "lente", moderate: "modérée", fast: "rapide" };
const PROPAGATION_LABEL: Record<string, string> = {
  stemCuttings: "bouturage de tige",
  division: "division",
  airLayering: "marcottage aérien",
  leafCuttings: "bouturage de feuille",
  layering: "marcottage",
  seeds: "semis",
  plantlets: "plantules",
  offsets: "rejets",
  tuberDivision: "division de tubercule",
  spores: "spores",
  runners: "stolons",
  grafting: "greffe",
  bulbDivision: "division de bulbe",
};

/**
 * `commonExamples` est un texte libre ("Cosmos bipinnatus (Garden cosmos), C.
 * sulphureus..."), pas un champ structure -- meilleur effort pour en extraire
 * le premier binome latin. Genre seul ou hybride intergenerique (x Genus) non
 * couverts : on laisse alors `scientificName` a null plutot que de deviner.
 */
// "spp"/"sp"/"cv"/"var" ne sont pas des epithetes d'espece mais des
// abreviations signifiant "plusieurs especes de ce genre" -- les traiter
// comme un binome ("Echinopsis spp") produit un faux nom scientifique
// injoignable dans aucune API externe. On retombe alors sur le genre seul.
const NOT_A_SPECIES_EPITHET = new Set(["spp", "sp", "cv", "var", "cvs"]);

export function extractScientificName(commonExamples?: string): string | null {
  if (!commonExamples) return null;
  // Le marqueur d'hybride (x/×) exige un espace de chaque cote : sans ca,
  // le "x" interne a un genre comme "Saxifraga" ou "Buxus" est backtracke
  // par le moteur regex et pris a tort pour ce marqueur (bug reel observe :
  // "Saxifraga (Saxifrage)..." -> genre extrait "Sa" + marqueur "x" +
  // "ifraga" -> "Sa ifraga").
  const m = commonExamples.match(/^([A-Z][a-z]+)(?:\s[×x]\s|\s+)([a-z][a-z-]+)/);
  if (m) return NOT_A_SPECIES_EPITHET.has(m[2].toLowerCase()) ? m[1] : `${m[1]} ${m[2]}`;
  // Pas d'epithete d'espece exploitable (ex. "Allium (Ornamental onion), A.
  // giganteum...", "Bonsai" n'etant meme pas un taxon) -- repli sur le genre
  // seul quand il est identifiable : toujours mieux qu'aucun nom, et rend la
  // fiche cherchable (recherche/photo) au moins au niveau du genre. La
  // logique anti-doublon de `seedPlantfolio` s'occupe des collisions.
  const genusOnly = commonExamples.match(/^([A-Z][a-z]+)\b/);
  return genusOnly ? genusOnly[1] : null;
}

function averageInterval(entry: PlantfolioRawEntry): number | null {
  const values = [entry.springInterval, entry.summerInterval, entry.fallInterval, entry.winterInterval].filter(
    (v): v is number => typeof v === "number" && v > 0,
  );
  if (values.length === 0) return null;
  return Math.max(1, Math.round(values.reduce((a, b) => a + b, 0) / values.length));
}

/**
 * Retour utilisateur (2026-09-19) : "pas d'orchidees dans la bibliotheque"
 * -- en realite si, mais sous des noms anglais (plantfolio n'a pas de
 * version francaise, voir commentaire plus haut sur description/careTips)
 * que personne ne pense a chercher en francais. Cle = `id` plantfolio (pas
 * typeName, qui change si le dataset est mis a jour).
 *
 * Traduction quasi complete des 663 fiches importees (demande explicite,
 * 2026-09-19), vocabulaire horticole francais etabli plutot qu'une
 * traduction mot a mot -- mais a cette echelle (600+ noms), pas verifiee
 * entree par entree comme les 5 corrections initiales (orchidees). Un nom
 * de cultivar sans equivalent francais etabli (ex. "Philodendron Congo",
 * genre + nom propre deja utilise tel quel en horticulture francophone)
 * est delibiremment laisse hors de cette table plutot que traduit au
 * hasard. Signaler toute correction necessaire au fil des retours.
 */
const COMMON_NAME_FR_OVERRIDES: Record<string, string> = {
  epiphyllum: "Cactus orchidée",
  "dendrobium-orchid": "Orchidée Dendrobium",
  "oncidium-orchid": "Orchidée Oncidium",
  paphiopedilum: "Sabot de Vénus",
  "vanda-orchid": "Orchidée Vanda",
  abelia: "Abélia",
  acacia: "Acacia",
  "acorn-squash": "Courge poivrée",
  adenium: "Rose du désert",
  "adzuki-bean": "Haricot azuki",
  agapanthus: "Agapanthe",
  agastache: "Agastache",
  "aglaonema-pink-star": "Aglaonema rose",
  ajuga: "Bugle rampante",
  alfalfa: "Luzerne",
  allium: "Ail d'ornement",
  almond: "Amandier",
  "alocasia-black-velvet": "Alocasia velours noir",
  "alocasia-cuprea": "Alocasia cuivré",
  "alocasia-dragon-scale": "Alocasia écailles de dragon",
  "alocasia-stingray": "Alocasia raie manta",
  "alocasia-zebrina": "Alocasia zébré",
  "alpine-aster": "Aster des Alpes",
  "alpine-plants": "Plantes alpines",
  alyssum: "Alysse",
  amaranth: "Amarante",
  "amaranth-grain": "Amarante à grain",
  "amazon-sword": "Épée d'Amazonie",
  anemone: "Anémone",
  angelonia: "Angélonia",
  "anthurium-bird-nest": "Anthurium nid d'oiseau",
  "anthurium-clarinervium": "Anthurium velours",
  "anthurium-crystallinum": "Anthurium cristallin",
  "anthurium-magnificum": "Anthurium magnifique",
  "anthurium-vittarifolium": "Anthurium à feuilles rubanées",
  "anthurium-warocqueanum": "Anthurium reine",
  apricot: "Abricotier",
  "aquatic-plants": "Plantes aquatiques",
  "armenian-cucumber": "Concombre arménien",
  arrowhead: "Sagittaire",
  artichoke: "Artichaut",
  arugula: "Roquette",
  "arugula-microgreens": "Pousses de roquette",
  arborvitae: "Thuya",
  "ficus-audrey": "Ficus banyan",
  shiso: "Pérille de Nankin",
  ash: "Frêne",
  asparagus: "Asperge",
  "asparagus-setaceus": "Asperge plumeuse",
  aspen: "Peuplier tremble",
  asters: "Asters",
  astilbe: "Astilbe",
  aubrieta: "Aubriète",
  avocado: "Avocatier",
  azaleas: "Azalées",
  "bald-cypress": "Cyprès chauve",
  bamboo: "Bambou",
  "bamboo-palm": "Palmier bambou",
  baobab: "Baobab",
  barberry: "Épine-vinette",
  barley: "Orge",
  beans: "Haricots",
  "bears-paw": "Patte d'ours",
  beautyberry: "Callicarpe",
  "bee-balm": "Monarde",
  beech: "Hêtre",
  "beet-greens": "Fanes de betterave",
  begonia: "Bégonia",
  "begonia-angel-wing": "Bégonia ailes d'ange",
  "begonia-rex": "Bégonia Rex",
  "begonia-wax": "Bégonia des jardins",
  "bell-peppers": "Poivrons",
  "big-bluestem": "Andropogon géant",
  birch: "Bouleau",
  "bird-of-paradise-white": "Oiseau de paradis blanc",
  "bitter-melon": "Margose",
  "black-eyed-susan": "Rudbeckie",
  "black-pepper": "Poivrier noir",
  blackberries: "Mûres",
  "blazing-star": "Liatris",
  blechnum: "Blechnum nain",
  "bleeding-heart": "Cœur-de-Marie",
  "blue-fescue": "Fétuque bleue",
  "blue-grama": "Bouteloua gracieux",
  blueberries: "Myrtilles",
  "bodhi-tree": "Figuier des pagodes",
  "bog-plants": "Plantes de tourbière",
  "bok-choy": "Pak-choï",
  bonsai: "Bonsaï",
  borage: "Bourrache",
  "boston-ivy": "Vigne vierge",
  bottlebrush: "Callistémon",
  boxwood: "Buis",
  "bristlecone-pine": "Pin aristé",
  "bromeliad-aechmea": "Aechmea",
  "bromeliad-guzmania": "Guzmania",
  "bromeliad-neoregelia": "Néorégélia",
  bromeliads: "Broméliacées",
  "buckwheat-grain": "Sarrasin",
  bulbs: "Bulbes",
  "burning-bush": "Fusain ailé",
  "butterfly-bush": "Buddleia",
  "butterfly-weed": "Asclépiade tubéreuse",
  "butternut-squash": "Courge butternut",
  butterwort: "Grassette",
  "button-fern": "Fougère bouton",
  cacao: "Cacaoyer",
  cacti: "Cactus",
  "calathea-makoyana": "Calathea paon",
  "calathea-medallion": "Calathea médaillon",
  "calathea-musaica": "Calathea réseau",
  "calathea-ornata": "Calathea rayée",
  "calathea-rattlesnake": "Calathea serpent à sonnette",
  "calathea-white-fusion": "Calathea fusion blanche",
  "calathea-white-star": "Calathea étoile blanche",
  "calathea-zebrina": "Calathea zébrée",
  calendula: "Souci",
  "calla-lily": "Arum",
  camellia: "Camélia",
  "campanula-alpine": "Campanule des Alpes",
  "campanula-garden": "Campanule à grosses fleurs",
  canna: "Balisier",
  "cape-gooseberry": "Coqueret du Pérou",
  cardamom: "Cardamome",
  "carnivorous-plant": "Dionée attrape-mouche",
  "carolina-jessamine": "Jasmin de Caroline",
  carrots: "Carottes",
  caryopteris: "Caryoptéris",
  cashew: "Anacardier",
  cassava: "Manioc",
  catalpa: "Catalpa",
  catmint: "Népéta",
  catnip: "Herbe à chat",
  cattails: "Massette",
  cedar: "Cèdre",
  celery: "Céleri",
  celosia: "Célosie",
  chamomile: "Camomille",
  cherries: "Cerises",
  "cherry-blossom": "Cerisier à fleurs",
  "cherry-tomato": "Tomate cerise",
  chestnut: "Châtaignier",
  chickpea: "Pois chiche",
  "chinese-chives": "Ciboulette chinoise",
  "chinese-elm": "Orme de Chine",
  chionodoxa: "Gloire des neiges",
  "christmas-cactus": "Cactus de Noël",
  chrysanthemums: "Chrysanthèmes",
  cinnamon: "Cannelier",
  clematis: "Clématite",
  cleome: "Cléome",
  climbers: "Plantes grimpantes",
  "climbing-hydrangea": "Hortensia grimpant",
  clivia: "Clivia",
  clove: "Giroflier",
  "clover-sprouts": "Pousses de trèfle",
  "clover-white": "Trèfle blanc",
  "coast-redwood": "Séquoia à feuilles d'if",
  "cobra-lily": "Darlingtonie",
  coconut: "Cocotier",
  "coffee-plant": "Caféier",
  "cold-hardy-evergreens": "Persistants rustiques",
  columbine: "Ancolie",
  comfrey: "Consoude",
  "common-milkweed": "Asclépiade commune",
  "compass-plant": "Silphium boussole",
  coneflower: "Échinacée",
  conifers: "Conifères",
  "cool-season-annuals": "Annuelles de saison fraîche",
  coreopsis: "Coréopsis",
  corn: "Maïs",
  "corpse-flower": "Fleur cadavre",
  cosmos: "Cosmos",
  cotoneaster: "Cotonéaster",
  cotton: "Cotonnier",
  crabapple: "Pommier d'ornement",
  cranberry: "Canneberge",
  "creeping-jenny": "Lysimaque nummulaire",
  "creeping-phlox": "Phlox rampant",
  "creeping-thyme": "Serpolet",
  "crepe-myrtle": "Lilas des Indes",
  "cress-garden": "Cresson alénois",
  crocosmia: "Crocosmia",
  crocus: "Crocus",
  "crocus-sativus": "Crocus à safran",
  crossvine: "Bignone",
  cucumbers: "Concombres",
  "culvers-root": "Véronicastre de Virginie",
  cumin: "Cumin",
  currant: "Groseillier",
  daffodils: "Jonquilles",
  "dahlia-annual": "Dahlia annuel",
  daikon: "Radis daïkon",
  daisies: "Marguerites",
  "dandelion-greens": "Feuilles de pissenlit",
  daphne: "Daphné",
  dates: "Dattier",
  "dawn-redwood": "Métaséquoia",
  daylilies: "Hémérocalles",
  "deciduous-trees": "Arbres à feuilles caduques",
  "deer-fern": "Blechnum en épi",
  delphinium: "Pied-d'alouette vivace",
  "desert-trees": "Arbres du désert",
  dianthus: "Œillet",
  "dianthus-alpine": "Œillet des Alpes",
  "dianthus-annual": "Œillet de Chine",
  "dianthus-carnation": "Œillet giroflée",
  "dieffenbachia-compact": "Dieffenbachia nain",
  dogwood: "Cornouiller",
  "dracaena-song-of-india": "Dracaena panaché",
  "dragon-blood-tree": "Dragonnier de Socotra",
  "dragon-fruit": "Fruit du dragon",
  "drosera-capensis": "Drosera du Cap",
  duckweed: "Lentille d'eau",
  "dusty-miller": "Cinéraire maritime",
  "easter-cactus": "Cactus de Pâques",
  eggplant: "Aubergine",
  elderberry: "Sureau",
  elm: "Orme",
  endive: "Endive",
  epazote: "Épazote",
  epiphytes: "Épiphytes",
  eucalyptus: "Eucalyptus",
  euonymus: "Fusain",
  "euphorbia-tirucalli": "Euphorbe crayon",
  "european-cornflower": "Bleuet",
  "european-fan-palm": "Chamérops",
  "false-aralia": "Faux aralia",
  "false-indigo": "Faux indigo",
  "fava-bean": "Fève",
  fennel: "Fenouil",
  "fenugreek-sprouts": "Pousses de fenugrec",
  "field-scabious": "Scabieuse des champs",
  fig: "Figuier",
  fir: "Sapin",
  flax: "Lin",
  "flowering-shrubs": "Arbustes à fleurs",
  "forget-me-not": "Myosotis",
  forsythia: "Forsythia",
  "four-o-clock": "Belle de nuit",
  foxglove: "Digitale",
  freesia: "Freesia",
  fritillaria: "Fritillaire",
  "fruit-trees": "Arbres fruitiers",
  fuchsia: "Fuchsia",
  gaillardia: "Gaillarde",
  garlic: "Ail",
  gaura: "Gaura",
  gentian: "Gentiane",
  geraniums: "Géraniums",
  "gerbera-daisy": "Gerbera",
  "giant-sequoia": "Séquoia géant",
  "giant-water-lily": "Victoria (nénuphar géant)",
  ginger: "Gingembre",
  ginkgo: "Ginkgo",
  ginseng: "Ginseng",
  gladiolus: "Glaïeul",
  gloxinia: "Gloxinia",
  "goji-berry": "Baie de goji",
  goldenrod: "Verge d'or",
  "goldfish-plant": "Plante poisson rouge",
  gomphrena: "Amarante globe",
  gooseberry: "Groseillier à maquereau",
  grapefruit: "Pamplemoussier",
  grapes: "Raisin",
  grasses: "Graminées",
  "great-mullein": "Bouillon blanc",
  "ground-cherry": "Coqueret",
  groundcovers: "Couvre-sols",
  guava: "Goyavier",
  gymnocalycium: "Cactus menton",
  habanero: "Piment habanero",
  "hardy-geranium": "Géranium vivace",
  "hardy-hibiscus": "Hibiscus rustique",
  hazelnut: "Noisetier",
  helenium: "Hélénie",
  heliconia: "Héliconia",
  hellebore: "Hellébore",
  hemp: "Chanvre",
  heuchera: "Heuchère",
  holly: "Houx",
  hollyhock: "Rose trémière",
  "holy-basil": "Basilic sacré",
  honeysuckle: "Chèvrefeuille",
  hops: "Houblon",
  hornbeam: "Charme",
  hornwort: "Cornifle",
  horseradish: "Raifort",
  horsetail: "Prêle",
  hostas: "Hostas",
  hyacinth: "Jacinthe",
  hydrangeas: "Hortensias",
  "ice-plant": "Ficoïde glaciale",
  "indian-grass": "Sorghastre",
  "iris-dutch": "Iris de Hollande",
  irises: "Iris",
  ironweed: "Vernonie",
  "italian-cypress": "Cyprès d'Italie",
  ixora: "Ixora",
  jacaranda: "Jacaranda",
  jackfruit: "Jaquier",
  "japanese-anemone": "Anémone du Japon",
  "japanese-forest-grass": "Hakonechloa",
  "japanese-maple": "Érable du Japon",
  "japanese-painted-fern": "Fougère peinte du Japon",
  "japanese-wisteria": "Glycine du Japon",
  "java-fern": "Fougère de Java",
  "java-moss": "Mousse de Java",
  "jerusalem-artichoke": "Topinambour",
  "joe-pye-weed": "Eupatoire pourpre",
  "joshua-tree": "Arbre de Josué",
  jujube: "Jujubier",
  juniper: "Genévrier",
  jute: "Jute",
  "kalanchoe-luciae": "Kalanchoe pagaie",
  "kapok-tree": "Fromager",
  kniphofia: "Tritome",
  "knockout-rose": "Rosier Knock Out",
  "lambs-ear": "Oreille d'agneau",
  lamium: "Lamier",
  lantana: "Lantana",
  larch: "Mélèze",
  larkspur: "Pied-d'alouette annuel",
  lavender: "Lavande",
  "lawn-turf": "Gazon",
  leadplant: "Amorphe",
  "leafy-greens": "Légumes-feuilles",
  leek: "Poireau",
  "lemon-balm": "Mélisse",
  "lemon-cypress": "Cyprès citron",
  lemongrass: "Citronnelle",
  lentil: "Lentille",
  lilac: "Lilas",
  lilies: "Lis",
  "lily-calla-mini": "Petit arum",
  "lily-of-the-valley": "Muguet",
  "lily-tiger": "Lis tigré",
  lime: "Limettier",
  "limelight-hydrangea": "Hortensia Limelight",
  linden: "Tilleul",
  "lipstick-plant": "Plante rouge à lèvres",
  liriope: "Liriope",
  lisianthus: "Lisianthus",
  lithops: "Cailloux vivants",
  "little-bluestem": "Andropogon à balais",
  lobelia: "Lobélie",
  longan: "Longanier",
  loquat: "Néflier du Japon",
  lotus: "Lotus",
  "lucky-bamboo": "Bambou porte-bonheur",
  luffa: "Éponge végétale",
  lupine: "Lupin",
  lychee: "Litchi",
  macadamia: "Macadamier",
  magnolia: "Magnolier",
  "magnolia-stellata": "Magnolia étoilé",
  "majesty-palm": "Palmier majesté",
  "malabar-spinach": "Épinard de Malabar",
  mammillaria: "Cactus coussin",
  mandarin: "Mandarinier",
  mango: "Manguier",
  mangrove: "Palétuvier",
  maple: "Érable",
  "marigold-african": "Œillet d'Inde",
  marigolds: "Tagètes",
  "marimo-moss-ball": "Boule de mousse Marimo",
  "maximilian-sunflower": "Tournesol de Maximilien",
  "meadow-cranesbill": "Géranium des prés",
  "meadow-sage": "Sauge des prés",
  medinilla: "Médinilla",
  "mexican-hat": "Chapeau mexicain",
  "microsorum-diversifolium": "Fougère patte de kangourou",
  "microsorum-musifolium": "Fougère crocodile",
  millet: "Millet",
  mint: "Menthe",
  "mondo-grass": "Ophiopogon",
  "monkey-puzzle-tree": "Désespoir des singes",
  moonflower: "Ipomée de lune",
  moringa: "Moringa",
  "morning-glory": "Ipomée volubilis",
  "mountain-laurel": "Kalmia",
  mulberry: "Mûrier",
  "mung-bean": "Haricot mungo",
  muscari: "Muscari",
  "mustard-greens": "Feuilles de moutarde",
  nandina: "Bambou sacré",
  nasturtium: "Capucine",
  nectarine: "Nectarinier",
  neem: "Margousier",
  nepenthes: "Népenthès",
  "nephrolepis-cordifolia": "Néphrolépis citron",
  "new-england-aster": "Aster de Nouvelle-Angleterre",
  ninebark: "Physocarpe",
  "norfolk-island-pine": "Araucaria de Norfolk",
  nutmeg: "Muscadier",
  oak: "Chêne",
  oats: "Avoine",
  "oil-palm": "Palmier à huile",
  okra: "Gombo",
  "old-lady-cactus": "Cactus vieille dame",
  oleander: "Laurier-rose",
  "onions-garlic": "Oignons et ail",
  orange: "Oranger",
  oregano: "Origan",
  "ornamental-allium": "Ail d'ornement géant",
  "ornamental-kale": "Chou d'ornement",
  "ornamental-sage": "Sauge d'ornement",
  osmanthus: "Osmanthe",
  oxalis: "Oxalis (trèfle porte-bonheur)",
  pachysandra: "Pachysandra",
  "painted-daisy": "Pyrèthre",
  "pampas-grass": "Herbe de la pampa",
  papaya: "Papayer",
  parodia: "Cactus boule",
  parsnip: "Panais",
  "passion-flower": "Passiflore",
  "passion-fruit": "Fruit de la passion",
  pawpaw: "Asiminier",
  "peace-lily-sensation": "Spathiphyllum géant",
  peanut: "Arachide",
  pear: "Poirier",
  peas: "Petits pois",
  pecan: "Pacanier",
  pennisetum: "Herbe aux écouvillons",
  penstemon: "Penstémon",
  peony: "Pivoine",
  peppermint: "Menthe poivrée",
  persimmon: "Plaqueminier",
  "petunia-grandiflora": "Pétunia à grandes fleurs",
  "philodendron-brandtianum": "Philodendron argenté",
  "philodendron-pink-princess": "Philodendron princesse rose",
  "philodendron-selloum": "Philodendron arborescent",
  "philodendron-silver": "Philodendron argenté",
  phlebodium: "Fougère bleue",
  phlox: "Phlox",
  "phoenix-roebelenii": "Palmier dattier nain",
  photinia: "Photinia",
  pickerelweed: "Pontédérie",
  pieris: "Pieris",
  "pigeon-pea": "Pois d'Angole",
  pine: "Pin",
  pineapple: "Ananas",
  "pink-muhly": "Herbe rose de Muhlenberg",
  pistachio: "Pistachier",
  "pitcher-plant": "Sarracénie",
  plantain: "Bananier plantain",
  plum: "Prunier",
  plumbago: "Plumbago",
  podocarpus: "Podocarpe",
  pomegranate: "Grenadier",
  pomelo: "Pomelo",
  poplar: "Peuplier",
  poppy: "Coquelicot",
  portulaca: "Pourpier à grandes fleurs",
  potatoes: "Pommes de terre",
  "prairie-coneflower": "Rudbeckie des prairies",
  "prairie-dock": "Silphium des prairies",
  "prairie-dropseed": "Sporobole à graines tombantes",
  "prayer-plants": "Plantes qui prient",
  "prickly-pear": "Figuier de Barbarie",
  primrose: "Primevère",
  "primula-alpine": "Primevère des Alpes",
  privet: "Troène",
  purslane: "Pourpier",
  pyracantha: "Buisson ardent",
  quince: "Cognassier",
  quinoa: "Quinoa",
  "rabbits-foot-fern": "Fougère patte de lapin",
  radicchio: "Chicorée rouge",
  rambutan: "Ramboutan",
  ranunculus: "Renoncule",
  raspberries: "Framboises",
  "rat-tail-cactus": "Cactus queue de rat",
  "rattlesnake-master": "Eryngium à feuilles de yucca",
  "red-clover": "Trèfle rouge",
  redbud: "Gainier",
  "redbud-chinese": "Gainier de Chine",
  "resurrection-fern": "Fougère de résurrection",
  rhubarb: "Rhubarbe",
  rice: "Riz",
  "river-birch": "Bouleau noir",
  "rose-of-sharon": "Hibiscus des jardins",
  "rubber-tree-hevea": "Hévéa",
  "russian-sage": "Perovskia",
  rutabaga: "Rutabaga",
  rye: "Seigle",
  safflower: "Carthame",
  saguaro: "Cactus saguaro",
  salsify: "Salsifis",
  "sansevieria-cylindrica": "Sansevieria cylindrique",
  "sansevieria-hahnii": "Sansevieria nain",
  scabiosa: "Scabieuse",
  scallion: "Oignon vert",
  schefflera: "Arbre ombrelle",
  scilla: "Scille",
  "sedum-groundcover": "Orpin rampant",
  "sedum-perennials": "Orpin vivace",
  serviceberry: "Amélanchier",
  sesame: "Sésame",
  "shasta-daisy": "Marguerite Shasta",
  "side-oats-grama": "Bouteloua à épis latéraux",
  sisal: "Sisal",
  "smoke-tree": "Arbre à perruque",
  "smooth-aster": "Aster lisse",
  snapdragon: "Gueule-de-loup",
  snowdrop: "Perce-neige",
  sorghum: "Sorgho",
  sorrel: "Oseille",
  "spanish-moss": "Barbe espagnole",
  spinach: "Épinard",
  spirea: "Spirée",
  "split-rock": "Plante caillou fendu",
  spruce: "Épicéa",
  "st-johns-wort": "Millepertuis",
  "star-cactus": "Cactus étoile",
  "star-jasmine": "Jasmin étoilé",
  starfruit: "Carambole",
  statice: "Statice",
  stephanotis: "Stéphanotis",
  stevia: "Stévia",
  stock: "Giroflée des jardins",
  strawberries: "Fraises",
  streptocarpus: "Streptocarpus",
  "string-of-bananas": "Collier de bananes",
  "string-of-dolphins": "Collier de dauphins",
  "string-of-needles": "Collier d'aiguilles",
  "string-of-rubies": "Collier de rubis",
  "string-of-turtles": "Collier de tortues",
  "succulent-aloe-v-black": "Aloé noir",
  sugarcane: "Canne à sucre",
  sundew: "Rossolis",
  sunflower: "Tournesol",
  "swamp-milkweed": "Asclépiade des marais",
  "sweet-pea": "Pois de senteur",
  "sweet-potato-vine": "Ipomée patate douce",
  "sweet-william": "Œillet de poète",
  "sweet-woodruff": "Aspérule odorante",
  sweetgum: "Copalme d'Amérique",
  "switchgrass-prairie": "Panic érigé",
  sycamore: "Platane",
  tamarind: "Tamarinier",
  "tea-plant": "Théier",
  "thanksgiving-cactus": "Cactus de Thanksgiving",
  thistle: "Chardon boule",
  tobacco: "Tabac",
  tomatillo: "Tomatille",
  "tradescantia-purple-heart": "Tradescantia pourpre",
  "tree-peony": "Pivoine arbustive",
  "trumpet-honeysuckle": "Chèvrefeuille trompette",
  "trumpet-vine": "Bignone trompette",
  tuberose: "Tubéreuse",
  "tuberous-begonias": "Bégonias tubéreux",
  "tulip-tree": "Tulipier de Virginie",
  turmeric: "Curcuma",
  "umbrella-palm": "Papyrus",
  vanilla: "Vanillier",
  verbena: "Verveine",
  "verbena-hybrid": "Verveine des jardins",
  veronica: "Véronique",
  viburnum: "Viorne",
  "vietnamese-coriander": "Coriandre vietnamienne",
  vinca: "Pervenche",
  viola: "Pensée sauvage",
  "vipers-bugloss": "Vipérine",
  "virginia-creeper": "Vigne vierge à cinq folioles",
  walnut: "Noyer",
  "warm-season-annuals": "Annuelles de saison chaude",
  "water-hawthorn": "Aubépine d'eau",
  "water-hyacinth": "Jacinthe d'eau",
  "water-iris": "Iris d'eau",
  "water-lettuce": "Laitue d'eau",
  "water-spinach": "Liseron d'eau",
  "watercress-sprouts": "Pousses de cresson",
  watermelon: "Pastèque",
  "weeping-willow": "Saule pleureur",
  weigela: "Weigela",
  wheat: "Blé",
  "wild-bergamot": "Monarde fistuleuse",
  "windmill-palm": "Palmier chanvre",
  "winter-melon": "Courge d'hiver",
  wisteria: "Glycine",
  "witch-hazel": "Hamamélis",
  "wollemi-pine": "Pin de Wollemi",
  "yard-long-bean": "Haricot kilomètre",
  yarrow: "Achillée millefeuille",
  "yellow-coneflower": "Échinacée jaune",
  "yerba-mate": "Yerba maté",
  yew: "If",
  "zebra-plant-aphelandra": "Aphélandre zébrée",
  zinnia: "Zinnia",
};

export interface MappedLibraryEntry {
  commonName: string;
  scientificName: string | null;
  family: null;
  careProfile: LibraryCareProfile;
}

export function mapPlantfolioEntry(entry: PlantfolioRawEntry): MappedLibraryEntry {
  const careProfile: LibraryCareProfile = {};

  if (entry.lightPreference) careProfile.exposure = LIGHT_LABEL[entry.lightPreference] ?? entry.lightPreference;
  if (entry.humidityPreference) careProfile.humidity = HUMIDITY_LABEL[entry.humidityPreference] ?? entry.humidityPreference;
  if (entry.temperaturePreference) careProfile.temperatureRange = `${entry.temperaturePreference[0]}-${entry.temperaturePreference[1]}°C`;
  if (entry.plantToxicity) careProfile.toxicity = TOXICITY_LABEL[entry.plantToxicity] ?? entry.plantToxicity;

  const substrateParts: string[] = [];
  if (entry.soilPhPreference) substrateParts.push(`pH ${PH_LABEL[entry.soilPhPreference] ?? entry.soilPhPreference}`);
  if (entry.drainagePreference) substrateParts.push(DRAINAGE_LABEL[entry.drainagePreference] ?? entry.drainagePreference);
  if (substrateParts.length) careProfile.substrate = substrateParts.join(", ");

  const interval = averageInterval(entry);
  if (interval) careProfile.watering = { recurrenceType: "FIXED_INTERVAL_DAYS", interval };

  const tipsParts: string[] = [];
  const seasonal = [
    entry.springInterval ? `printemps ${entry.springInterval}j` : null,
    entry.summerInterval ? `été ${entry.summerInterval}j` : null,
    entry.fallInterval ? `automne ${entry.fallInterval}j` : null,
    entry.winterInterval ? `hiver ${entry.winterInterval}j` : null,
  ].filter(Boolean);
  if (seasonal.length) tipsParts.push(`Arrosage indicatif par saison : ${seasonal.join(", ")}.`);
  // `description`/`careTips` sont en anglais (plantfolio n'a pas de version
  // francaise) -- volontairement exclus pour ne pas meler de l'anglais brut
  // a une application en francais. Les infos structurees qu'ils contiennent
  // (rusticite, multiplication, origine...) sont deja extraites ci-dessous.
  const extras: string[] = [];
  if (entry.origin) extras.push(`origine : ${entry.origin}`);
  if (entry.growthRate) extras.push(`croissance ${GROWTH_LABEL[entry.growthRate] ?? entry.growthRate}`);
  if (entry.propagationMethods?.length) {
    extras.push(`multiplication par ${entry.propagationMethods.map((m) => PROPAGATION_LABEL[m] ?? m).join(", ")}`);
  }
  if (entry.hardinessZones) extras.push(`zones de rusticité USDA ${entry.hardinessZones[0]}-${entry.hardinessZones[1]}`);
  if (extras.length) tipsParts.push(extras.join(" · ") + ".");
  if (tipsParts.length) careProfile.tips = tipsParts.join(" ");

  return {
    commonName: COMMON_NAME_FR_OVERRIDES[entry.id] ?? entry.typeName,
    scientificName: extractScientificName(entry.commonExamples),
    family: null,
    careProfile,
  };
}
